### ISSUE TITLE
Blank profile settings

### ISSUE THREAD

**Issue by altteo** [gitspeak/community#11]
![image.png](https://cdn.filestackcontent.com/g7yAEhcaRiK5nYh6VJjH)

**Comment by nemanjaglumac** [comment]
Yup. Just wanted to open the same issue. (Search works blazingly fast, btw). 
For me it happens only on community repo/channel. That's probably because we're not the owners (or admins) of that repo. 

Still, it would be nice to have some placeholder text, or some general settings that are not related to any particular repo.

**Comment by somebee** [comment]
We're reworking settings. Closing for now :)
